package mvc;


import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.SpringLayout;

import vista.SpringUtilities;


public class CasinoView extends javax.swing.JFrame {
    private static final String INITIAL_VALUE = "1";
    private CasinoModel m_model;
    /** Creates new form CalcView */
    public CasinoView(String titulo, CasinoModel model) {
        super(titulo);
    	m_model = model;
        m_model.setValue(this.INITIAL_VALUE);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        
    	this.getContentPane().setLayout(new BorderLayout());
    	
        
        m_inicioAuto = new javax.swing.JMenuItem("Inicio Automático");
        m_reset = new javax.swing.JMenuItem("Resetear");
        m_salir = new javax.swing.JMenuItem("Salir");
        m_archivo = new javax.swing.JMenu("archivo");
        m_usuario=new javax.swing.JMenu("Ususuario");
        m_partida=new javax.swing.JMenu("Partida");
		m_crearCuenta=new javax.swing.JMenuItem("Crear Cuenta e iniciar sesion");
		m_iniciarSesion=new javax.swing.JMenuItem("Iniciar Sesion");
		m_cerrarSesion=new javax.swing.JMenuItem("Cerrar Sesion");
		m_sentarMesa=new javax.swing.JMenuItem("Sentar en una Mesa");
		m_jugar=new javax.swing.JMenuItem("Jugar");
		m_barra = new javax.swing.JMenuBar();
        
        
		m_archivo.add(m_inicioAuto);
        m_archivo.add(m_reset);
        m_archivo.addSeparator();
        m_archivo.add(m_salir);
        m_barra.add(m_archivo);
        m_usuario.add(m_crearCuenta);
        m_usuario.add(m_iniciarSesion);
        m_usuario.add(m_cerrarSesion);
        m_usuario.add(m_sentarMesa);
        m_barra.add(m_usuario);
        m_partida.add(m_jugar);
        m_barra.add(m_partida);
        
        this.setJMenuBar(m_barra);
        /*****Status bar*****/
		statusPanel = new javax.swing.JPanel();
		statusPanel.setLayout(new BorderLayout());
		statusMsg1 = new javax.swing.JLabel("Estado: ");
		statusMsg2 = new javax.swing.JLabel();
		statusPanel.add(statusMsg1, BorderLayout.WEST);
		statusPanel.add(statusMsg2, BorderLayout.CENTER);
		//Agrega el panel de satus al sur del contenedor
		this.getContentPane().add(statusPanel, BorderLayout.SOUTH);
		
		
		juegosPane = new javax.swing.JTextPane();
		juegosPane.setText("resultados Partida 1 en mesa 1 :");
		scrollPaneLeft = new javax.swing.JScrollPane(juegosPane);

		/*****List*****/
		lista=new javax.swing.JTextArea();
		scrollPaneRight=new javax.swing.JScrollPane(lista);
		
		/*****leftPanel*****/
		rightPanel=new javax.swing.JPanel(new BorderLayout());
		rightPanel.add(scrollPaneRight,BorderLayout.CENTER);
		rightPanel.add(new javax.swing.JLabel("Usuarios Conectados"),BorderLayout.NORTH);

		/*****Split Panel*****/
		//Define un contenedor con division izq-der
		splitPane = new javax.swing.JSplitPane(JSplitPane.HORIZONTAL_SPLIT);
		splitPane.setRightComponent(rightPanel);
		splitPane.setLeftComponent(scrollPaneLeft);
		splitPane.setDividerLocation(400);
		this.getContentPane().add(splitPane, BorderLayout.CENTER);
		
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }// </editor-fold>//GEN-END:initComponents
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    
    private javax.swing.JMenuItem m_inicioAuto;
    private javax.swing.JMenuItem m_reset;
    private javax.swing.JMenuItem m_salir;
    private javax.swing.JMenu m_usuario;
    private javax.swing.JMenuItem m_crearCuenta;
    private javax.swing.JMenuItem m_iniciarSesion;
    private javax.swing.JMenuItem m_cerrarSesion;
    private javax.swing.JMenuItem m_sentarMesa;
    private javax.swing.JMenu m_archivo;
    private javax.swing.JMenu m_partida;
    private javax.swing.JMenuItem m_jugar;
    
    private javax.swing.JMenuBar m_barra;
    
    private javax.swing.JPanel statusPanel;
    private javax.swing.JLabel statusMsg1;
    private javax.swing.JLabel statusMsg2;
	
    private javax.swing.JTextPane juegosPane;
    private javax.swing.JScrollPane scrollPane,scrollPaneLeft,scrollPaneRight;
    private javax.swing.JTextArea lista;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
//    public void reset() {
//        m_totalTf.setText(INITIAL_VALUE);
//    }
//    
//    public String getUserInput() {
//        return m_userInputTf.getText();
//    }
//    
//    public void setTotal(String newTotal) {
//        m_totalTf.setText(newTotal);
//    }
    
    public void VentanaCrearCuenta() {

  
   		JFrame framecc = new JFrame("Crear Cuenta");
   		JPanel contentPane = new JPanel(new SpringLayout());
   		JLabel loggin = new JLabel("Loggin",JLabel.TRAILING);
   		JLabel passw1 = new JLabel("Password",JLabel.TRAILING);
   		JLabel passw2 = new JLabel("Password",JLabel.TRAILING);
   		JTextField campo1= new JTextField(10);
   		JPasswordField pass1 = new JPasswordField(10);
   		JPasswordField pass2 = new JPasswordField(10);
   		JButton botonCrear =new JButton ("Crear");
    	JButton botonCancelar =new JButton ("Cancelar");
    	JLabel statusMsg1 = new JLabel("Estado: ");
   		JLabel statusMsg2 = new JLabel();
    		
    		
    		//contentPane.add(tex1,SpringLayout.HEIGHT);
//    		contentPane.add(pass1,BorderLayout.NORTH);
//    		contentPane.add(pass2,BorderLayout.CENTER);
    	contentPane.add(loggin);
    	loggin.setLabelFor(campo1);
   		contentPane.add(campo1);
    		
   		contentPane.add(passw1);
    	passw1.setLabelFor(pass1);
    	contentPane.add(pass1);
    		
   		contentPane.add(passw2);
   		passw2.setLabelFor(pass2);
    	contentPane.add(pass2);
    		
   		contentPane.add(botonCrear);
   		contentPane.add(botonCancelar);
    		
   		contentPane.add(statusMsg1);
   		contentPane.add(statusMsg2);
    		
    		
   		SpringUtilities.makeCompactGrid(contentPane,
                  5, 2, //rows, cols
                  6, 6,        //initX, initY
                  6, 6);       //xPad, yPad

//    		contentPane.add(botonCrear,SpringLayout.SOUTH);
    	contentPane.setOpaque(true);
    		
//    		framecc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
   		framecc.setContentPane(contentPane);
    		
//    		framecc.setSize(300,200);
    	framecc.pack();
   		framecc.setLocation(150,150);
   		framecc.setVisible(true);
    

    }


    public void showError(String errMessage) {
        JOptionPane.showMessageDialog(this, errMessage);
    }
    
    public void addInicioAutoListener(ActionListener mal) {
        m_inicioAuto.addActionListener(mal);
    }
    public void addResetListener(ActionListener mal) {
        m_reset.addActionListener(mal);
    }
    public void addSalirListener(ActionListener mal) {
        m_salir.addActionListener(mal);
    }
    
    public void addCrearCuentaListener(ActionListener mal) {
        m_crearCuenta.addActionListener(mal);
    }
    public void addIniciarSesionListener(ActionListener mal) {
        m_iniciarSesion.addActionListener(mal);
    }
    public void addCerrarSesionListener(ActionListener mal) {
        m_cerrarSesion.addActionListener(mal);
    }
    public void addSentarMesaListener(ActionListener mal) {
        m_sentarMesa.addActionListener(mal);
    }
    public void addJugarListener(ActionListener mal) {
        m_jugar.addActionListener(mal);
    }

    public void setUsuario(String login) {
		//lista.SetText(login);
		// TODO Auto-generated method stub
		
	}
    public void setEstado(String estado) {
    	statusMsg2.setText(estado)
;    }
	public void addUsuario(String login) {
		
	
		lista.setText(login +'\n' + lista.getText());

		 

		
		// TODO Auto-generated method stub
		
	}

	public void setJuegosPane(String stringOut) {
		// TODO Auto-generated method stub
		juegosPane.setText(stringOut);
		
	}


//    public void addClearListener(ActionListener cal) {
//        m_clearBtn.addActionListener(cal);
//    }
}
